# Generated by Django 4.1 on 2023-01-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familybudgetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='incomes',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
