# Generated by Django 4.1 on 2023-01-23 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "familybudgetapp",
            "0004_category_expense_income_remove_transaction_budget_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Shared",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "Income"), ("EX", "Expense")], max_length=2
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="income",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="income",
            name="categories",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="budget",
            name="expenses",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="incomes",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="Income",
        ),
        migrations.AddField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomes",
                to="familybudgetapp.budget",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="categories",
            field=models.ManyToManyField(to="familybudgetapp.category"),
        ),
        migrations.AddField(
            model_name="shared",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="familybudgetapp.budget"
            ),
        ),
        migrations.AddField(
            model_name="shared",
            name="shared_with",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
