# Generated by Django 4.1 on 2023-01-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("familybudgetapp", "0006_alter_budget_owner_alter_transaction_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="categories",
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="familybudgetapp.category",
            ),
            preserve_default=False,
        ),
    ]
