# Generated by Django 4.1 on 2023-01-24 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("familybudgetapp", "0007_remove_transaction_categories_transaction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shared",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_with",
                to="familybudgetapp.budget",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
