# Generated by Django 4.1 on 2023-01-21 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=2)),
                ('category', models.CharField(choices=[('HOUSING', 'Housing'), ('TRANSPORTATION', 'Transportation'), ('FOOD', 'Food'), ('UTILITIES', 'Utilities'), ('INSURANCE', 'Insurance'), ('HEALTHCARE', 'Medical & Healthcare'), ('SAVINGS', 'Savings, Investing, & Debt Payments'), ('PERSONAL', 'Personal spendings'), ('ENTERTAINMENT', 'Recreation & Entertainment'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familybudgetapp.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familybudgetapp.person'),
        ),
    ]
